### ISSUE TITLE
Multiple items on error

### ISSUE THREAD

**Issue by AlejandroAkbal** [Igloczek/n8n-nodes-pocketbase-admin#1]
Hey, saw your message on the other repo

Basically the critical error I mentioned is this:

When a pocketbase-admin node has an error, for example, creating or finding a record, the output instead of 1 item, is **multiple items**, one for each line, or json lines, something like that
Which causes the next nodes to execute multiple times, causing more errors in the n8n workflow

This error might be happening because this library might not handle errors correctly

Version 1.0.0

**Comment by MattCarneiro** [comment]
this issue is still with this fork?

**Comment by MattCarneiro** [comment]
Could you please elaborate more how do you get this "multiple items" error? I tried to reproduce but only got a typical error

**Comment by AlejandroAkbal** [comment]
I dont know, I've been using HTTP node since this and since then, I will close as a possible false positive

**Comment by Igloczek** [comment]
you can configure how is should behave on the error, it's a standard n8n config option on any node

![CleanShot 2025-01-14 at 21 59 36](https://github.com/user-attachments/assets/23984101-6965-4c36-88f5-45d3940dda19)

but in general, if it fails on multiple items, you will get multiple errors, it's expected behavior, not a bug
